### ISSUE TITLE
before, beforeEach doesn't work

### ISSUE THREAD

**Issue by CamTosh** [SilentCicero/wafr#2]
Hi !

Before and beforeEach method doesn't work. Can you fix that ? :)

I try [this code](https://github.com/SilentCicero/wafr/blob/master/docs/user-guide.md#using-before-beforeeach-after-aftereach) :
```    
    function before_test_method1() {
        anotherValue = 8;
    }

    function test_method1() {
        assertEq(someValue, uint(3), "some value should be 3");
        assertEq(anotherValue, uint(8), "another value should be 8");
    }
```

Output : 
```
Error: [wafr] ERROR: while compiling contracts in path wafr/src: wafr/Test.sol:4:3: Warning: No visibility specified. Defaulting to "public".
  function () payable {}
  ^--------------------^

    at throwError (wafr/node_modules/wafr/src/utils/index.js:11:9)
    at output.errors.forEach (wafr/node_modules/wafr/src/index.js:573:9)
    at Array.forEach (<anonymous>)
    at getInputSources (wafr/node_modules/wafr/src/index.js:572:21)
    at dir.readFiles (wafr/node_modules/wafr/src/utils/index.js:232:13)
    at wafr/node_modules/node-dir/lib/readfiles.js:110:34
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
```

## Version

- Mac OS
- Node v9.0.0
- Solc : Version: 0.4.18+commit.9cf6e910.Darwin.appleclang

**Comment by SilentCicero** [comment]
Yep, I will take a look!
